VacaYAY/VacaYAY.Web/Areas/Contracts/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Contracts.Pages;


[Authorize(Roles = InitialData.AdminRoleName)]
public class DeleteModel : PageModel
{
    private readonly IContractService _contractService;

    public DeleteModel(IContractService contractService)
    {
        _contractService = contractService;
    }

    [BindProperty]
  public Contract Contract { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var contract = await _contractService.GetByIdAsync((int)id);

        if (contract is null)
        {
            return NotFound();
        }
        else 
        {
            Contract = contract;
        }
        return Page();
    }

    public async Task<IActionResult> OnPostAsync(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }
        var contract = await _contractService.GetByIdAsync((int)id);

        if (contract is not null)
        {
            Contract = contract;
            await _contractService.DeleteContractAsync((int)id);
        }

        return RedirectToPage("./Index");
    }
}

VacaYAY/VacaYAY.Web/Areas/Contracts/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.DTOs;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Contracts.Pages;


[Authorize(Roles = InitialData.AdminRoleName)]
public class EditModel : PageModel
{
    private readonly IContractService _contractService;
    private readonly IHttpService _httpService;

    public EditModel(
        IContractService contractService,
        IHttpService httpService)
    {
        _contractService = contractService;
        _httpService = httpService;
    }

    [BindProperty(SupportsGet = true)]
    public ContractDTO ContractDTO { get; set; } = default!;

    [BindProperty]
    public IFormFile? ContractFile { get; set; }

    [BindProperty(SupportsGet = true)]
    public Contract Contract { get; set; } = default!;
    public IList<ContractType> ContractTypes { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        ContractTypes = await _contractService.GetContractTypesAsync();

        if (id is null)
        {
            return NotFound();
        }

        var contract = await _contractService.GetByIdAsync((int)id);
        if (contract is null)
        {
            return NotFound();
        }

        Contract = contract;

        ContractDTO.ContractFile = await _httpService.GetFormFileAsync(contract.DocumentUrl);

        ContractDTO = new ContractDTO()
        {
            Id = contract.Id,
            ContractTypeId = contract.Type.Id,
            EmployeeId = contract.Employee.Id,
            Number = contract.Number,
            StartDate = contract.StartDate,
            EndDate = contract.EndDate
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (ContractFile is not null)
        {
            ContractDTO.ContractFile = ContractFile;
        }

        var contractValidationResult = await _contractService.UpdateContractAsync(ContractDTO);

        if (!contractValidationResult.IsValid)
        {
            ModelState.Clear();
            foreach (var error in contractValidationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
            return Page();
        }

        Contract = await _contractService.GetByIdAsync(Contract.Id);
        ContractTypes = await _contractService.GetContractTypesAsync();

        return RedirectToPage("./Index");
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages
{
    public class CreateModel : PageModel
    {

        public CreateModel()
        {
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public IActionResult OnPostAsync()
        {
          if (!ModelState.IsValid ||  Employee == null)
            {
                return Page();
            }

            //_context.Employees.Add(Employee);
            //await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages
{
    [Authorize(Roles = InitialData.AdminRoleName)]
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeService _employeeService;

        public DeleteModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        [BindProperty]
      public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var employee = await _employeeService.GetByIdAsync(id);

            if (employee is null)
            {
                return NotFound();
            }
            else 
            {
                Employee = employee;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var employee = await _employeeService.GetByIdAsync(id);

            if (employee is not null)
            {
                Employee = employee;
                
                await _employeeService.SoftDeleteAsync(employee);
            }

            return RedirectToPage("./Index");
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeService _employeeService;
        public DetailsModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

      public required Employee Employee { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var employee = await _employeeService.GetByIdAsync(id);
            if (employee is null)
            {
                return NotFound();
            }
            else 
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using VacaYAY.Business;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.DTOs;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages;

[Authorize(Roles = InitialData.AdminRoleName)]
public class EditModel : PageModel
{
    private readonly IEmployeeService _employeeService;
    private readonly IPositionService _positionService;
    private readonly IContractService _contractService;
    private readonly IFileService _fileService;

    public EditModel(
        IEmployeeService employeeService,
        IPositionService positionService,
        IContractService contractService,
        IFileService fileService
        )
    {
        _employeeService = employeeService;
        _positionService = positionService;
        _contractService = contractService;
        _fileService = fileService;
    }

    [BindProperty(SupportsGet = true)]
    public EmployeeDTO EmployeeDTO { get; set; } = default!;

    [BindProperty(SupportsGet = true)]
    public ContractDTO ContractDTO { get; set; } = default!;
    [BindProperty]
    [Required(ErrorMessage = "Contract document is required.")]
    public required IFormFile ContractFile { get; set; }
    public IList<ContractType> ContractTypes { get; set; } = default!;
    public IList<Position> Positions { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(string id)
    {
        Positions = await _positionService.GetAllAsync();
        ContractTypes = await _contractService.GetContractTypesAsync();

        if (id is null)
        {
            return NotFound();
        }

        var employeeFromDb = await _employeeService.GetByIdAsync(id);
        if (employeeFromDb is null)
        {
            return NotFound();
        }
        EmployeeDTO = employeeFromDb;

        ContractDTO.StartDate = EmployeeDTO.EmploymentStartDate;

        ContractDTO.EmployeeId = employeeFromDb.Id;

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        Positions = await _positionService.GetAllAsync();

        var validationResult = await _employeeService.UpdateAsync(EmployeeDTO);

        if (!validationResult.IsValid)
        {
            ModelState.Clear();

            foreach (var error in validationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }


            return Page();
        }

        return RedirectToPage("./Index");
    }

    public async Task<IActionResult> OnPostAddContractAsync()
    {
        ContractDTO.ContractFile = ContractFile;
        var contractValidationResult = await _contractService.CreateContractAsync(ContractDTO);

        if (!contractValidationResult.IsValid)
        {
            ModelState.Clear();
            foreach (var error in contractValidationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }

            return Page();
        }

        return RedirectToAction("Index", nameof(Contracts));
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.DTOs;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages;

[Authorize(Roles = InitialData.AdminRoleName)]
public class IndexModel : PageModel
{
    private readonly IEmployeeService _employeeService;
    private readonly IPositionService _positionService;

    public IndexModel(
        IEmployeeService employeeService,
        IPositionService positionService)
    {
        _employeeService = employeeService;
        _positionService = positionService;
    }

    [BindProperty(SupportsGet = true)]
    public EmployeeSearchFilters Input { get; set; } = default!;

    [BindProperty(SupportsGet = true)]
    public int NumberOfFakeEmployeesToGenerate { get; set; }

    public IList<Employee> Employees { get; set; } = default!;
    public IList<Position> Positions { get; set; } = default!;

    public async Task OnGetAsync()
    {
        Employees = await _employeeService.SearchAsync(Input);
        Positions = await _positionService.GetAllAsync();
    }

    public async Task<IActionResult> OnPostSearchAsync()
    {
        Employees = await _employeeService.SearchAsync(Input);
        Positions = await _positionService.GetAllAsync();

        return Page();
    }

    public async Task<IActionResult> OnPostGenerateFakeEmployeesAsync()
    {
        await _employeeService.CreateFakesAsync(NumberOfFakeEmployeesToGenerate);

        Employees = await _employeeService.SearchAsync(Input);
        Positions = await _positionService.GetAllAsync();

        return Page();
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.VacationRequests;

public class CreateModel : PageModel
{
    private readonly IVacationService _vacationService;
    private readonly IEmployeeService _employeeService;

    public CreateModel(
        IVacationService vacationService,
        IEmployeeService employeeService
        )
    {
        _vacationService = vacationService;
        _employeeService = employeeService;
    }

    [BindProperty]
    public VacationRequest VacationRequest { get; set; } = default!;
    public IList<LeaveType> LeaveTypes { get; set; } = default!;

    [BindProperty]
    public int LeaveTypeId { get; set; } = default;
    public int TotalPotentialDaysOff => PotentialLastYearsDaysOff + PotentialNewDaysOff;
    public required int PotentialLastYearsDaysOff { get; set; } = default!;
    public required int PotentialNewDaysOff { get; set; } = default!;
    public Employee LoggedInEmployee { get; set; } = default!;

    private async Task<StatusCodeResult> Init()
    {
        LeaveTypes = await _vacationService.GetLeaveTypesAsync();

        if (!User.IsInRole(InitialData.AdminRoleName))
        {
            LeaveTypes = LeaveTypes.Where(lt => lt.Id != InitialData.CollectiveVacationLeaveType.Id).ToList();
        }

        Employee? loggedInEmployee = await _employeeService.GetLoggedInAsync(User);

        if (loggedInEmployee is null)
        {
            return StatusCode(StatusCodes.Status401Unauthorized);
        }
        LoggedInEmployee = loggedInEmployee;

        int potentiallyUsedDays = await _vacationService.GetPotentiallyUsedDaysAsync(LoggedInEmployee.Id);

        int overflow = Math.Max(potentiallyUsedDays - LoggedInEmployee.LastYearsDaysOffNumber, 0);
        PotentialLastYearsDaysOff = Math.Max(LoggedInEmployee.LastYearsDaysOffNumber - potentiallyUsedDays, 0);
        PotentialNewDaysOff = Math.Max(LoggedInEmployee.DaysOffNumber - overflow, 0);

        return StatusCode(StatusCodes.Status200OK);
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var result = await Init();
        if (result.StatusCode == StatusCodes.Status401Unauthorized)
        {
            return Unauthorized();
        }

        VacationRequest = new()
        {
            Comment = string.Empty,
            Employee = LoggedInEmployee,
            StartDate = DateTime.Now.Date.AddDays(1),
            EndDate = DateTime.Now.Date.AddDays(6),
            LeaveType = LeaveTypes.First()
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        var result = await Init();
        if (result.StatusCode == StatusCodes.Status401Unauthorized)
        {
            return Unauthorized();
        }

        Employee? loggedInEmployee = await _employeeService.GetLoggedInAsync(User);

        if (loggedInEmployee is null)
        {
            return NotFound();
        }

        VacationRequest.Employee = LoggedInEmployee;
        VacationRequest.LeaveType = LeaveTypes.Single(lt => lt.Id == LeaveTypeId);

        var requestValidationResult = await _vacationService.CreateVacationRequestAsync(VacationRequest, User);

        ModelState.Clear();
        if (!requestValidationResult.IsValid)
        {
            foreach (var error in requestValidationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }

            await Init();
            return Page();
        }

        return RedirectToPage("./Index");
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.VacationRequests
{
    public class DeleteModel : PageModel
    {
        private readonly IVacationService _vacationService;

        public DeleteModel(IVacationService vacationService)
        {
            _vacationService = vacationService;
        }

        [BindProperty]
        public VacationRequest VacationRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var vacationrequest = await _vacationService.GetVacationRequestByIdAsync((int)id);

            if (vacationrequest is null)
            {
                return NotFound();
            }
            else
            {
                VacationRequest = vacationrequest;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            await _vacationService.DeleteVacationRequestAsync((int)id, User);

            return RedirectToPage("./Index");
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Edit.cshtml
@page
@using VacaYAY.Data.Models;
@model VacaYAY.Web.Areas.Employees.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<div class="row justify-content-between">
    <div class="col-md-4">
        <h4>Employee</h4>
        <form method="post">
            <input type="hidden" asp-for="EmployeeDTO.Id" />
            <div class="form-floating mb-3">
                <input asp-for="EmployeeDTO.FirstName" class="form-control" />
                <label asp-for="EmployeeDTO.FirstName" class="control-label">First name</label>
                <span asp-validation-for="EmployeeDTO.FirstName" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="EmployeeDTO.LastName" class="form-control" />
                <label asp-for="EmployeeDTO.LastName" class="control-label">Last name</label>
                <span asp-validation-for="EmployeeDTO.LastName" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="EmployeeDTO.Address" class="form-control" />
                <label asp-for="EmployeeDTO.Address" class="control-label">Address</label>
                <span asp-validation-for="EmployeeDTO.Address" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="EmployeeDTO.Email" class="form-control" />
                <label asp-for="EmployeeDTO.Email" class="control-label">Email</label>
                <span asp-validation-for="EmployeeDTO.Email" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="EmployeeDTO.IdNumber" class="form-control" />
                <label asp-for="EmployeeDTO.IdNumber" class="control-label">ID number</label>
                <span asp-validation-for="EmployeeDTO.IdNumber" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="EmployeeDTO.DaysOffNumber" class="form-control" />
                <label asp-for="EmployeeDTO.DaysOffNumber" class="control-label">Number of days off</label>
                <span asp-validation-for="EmployeeDTO.DaysOffNumber" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                @Html.DropDownListFor(m => m.EmployeeDTO.PositionId, new SelectList(@Model.Positions, nameof(Position.Id), nameof(Position.Caption)),
                new {@class="form-control dropdown-toggle"})
                <label for="Position">Position</label>
            </div>

            <div class="form-floating mb-3">
                <input type="date" asp-for="EmployeeDTO.EmploymentStartDate" class="form-control" />
                <label asp-for="EmployeeDTO.EmploymentStartDate" class="control-label">Employment start date</label>
                <span asp-validation-for="EmployeeDTO.EmploymentStartDate" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input type="date" asp-for="EmployeeDTO.EmploymentEndDate" class="form-control" />
                <label asp-for="EmployeeDTO.EmploymentEndDate" class="control-label">Employment end date</label>
                <span asp-validation-for="EmployeeDTO.EmploymentEndDate" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
        </form>
    </div>

    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            @Html.HiddenFor(m => m.ContractDTO.Id)
            @Html.HiddenFor(m => m.ContractDTO.EmployeeId)
            <h2>Add contract</h2>
            <div class="form-floating mb-3">
                <input asp-for="ContractDTO.Number" class="form-control" aria-required="true" />
                <label asp-for="ContractDTO.Number">Contract number</label>
                <span asp-validation-for="ContractDTO.Number" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="ContractDTO.StartDate" 
                min="@(Model.EmployeeDTO.EmploymentStartDate.Date.ToString("yyyy-MM-dd"))"
                class="form-control" type="date" aria-required="true" />
                <label asp-for="ContractDTO.StartDate">Contract start date</label>
                <span asp-validation-for="ContractDTO.StartDate" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="ContractDTO.EndDate"
                class="form-control" type="date" aria-required="true" />
                <label asp-for="ContractDTO.EndDate">Contract end date</label>
                <span asp-validation-for="ContractDTO.EndDate" class="text-danger"></span>
            </div>  
            <div class="form-floating mb-3">
                @Html.DropDownListFor(m => m.ContractDTO.ContractTypeId, new SelectList(@Model.ContractTypes, nameof(Contract.Type.Id), nameof(Contract.Type.Name)),
                new {@class="form-control dropdown-toggle"})
                <label for="Contract type">Contract type</label>
            </div>
            <div class="form-floating mb-3">
                <p asp-for="ContractFile">Contract document</p>
                <input class="file" asp-for="ContractFile" accept=".pdf,.doc,.docx" type="file" value="Upload file" />
            </div>
            <div class="form-floating mb-3">
                <input type="submit" asp-page-handler="AddContract" value="Save" class="btn btn-primary" />
            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Index.cshtml
@page
@using VacaYAY.Data;
@using VacaYAY.Data.Models;
@model VacaYAY.Web.Areas.Employees.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Employees</h1>

<div class="row justify-content-between">
    <div class="col-md-4">
        <h3>Search</h3>
        <form method="post">
            @if (User.IsInRole(InitialData.AdminRoleName))
            {
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" asp-for="Input.EmployeeFullName" />
                    <label asp-for="Input.EmployeeFullName">Full name</label>
                </div>
            }
            <div class="form-floating mb-3">
                <input type="date" class="form-control" asp-for="Input.EmploymentStartDate" />
                <label asp-for="Input.EmploymentStartDate">Employment start date</label>
            </div>
            <div class="form-floating mb-3">
                <input type="date" class="form-control" asp-for="Input.EmploymentEndDate" />
                <label asp-for="Input.EmploymentEndDate">Employment end date</label>
            </div>
            <div class="form-floating mb-3">
                <h5>Positions</h5>
                <select asp-for="Input.PositionIds"
                        asp-items="@(new SelectList(Model.Positions, nameof(Position.Id), nameof(Position.Caption)))"
                        name="@(nameof(Model.Input)).@(nameof(Model.Input.PositionIds))"
                        class="selectpicker positions-select"
                        multiple="multiple">
                </select>
            </div>
            <button id="searchSubmit" asp-page-handler="Search" type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>

    <div class="col-md-4">
        <h4>Load existing employees from the old system</h4>
        <form method="post">
            <label asp-for="NumberOfFakeEmployeesToGenerate">Number of fake employees</label>
            <input type="number" min="1" class="form-control mb-3" asp-for="NumberOfFakeEmployeesToGenerate" name="numberOfFakeEmployeesToGenerate" value="2" />

            <button id="generateSubmit" asp-page-handler="GenerateFakeEmployees" type="submit" class="btn btn-primary">Load</button>
        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].IdNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].DaysOffNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].LastYearsDaysOffNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].EmploymentStartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].EmploymentEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].InsertDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employees[0].DeleteDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Employees)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DaysOffNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastYearsDaysOffNumber)
                </td>
                <td>
                    @Convert.ToDateTime(item.EmploymentStartDate).ToString("dd/MMMM/yyyy")
                </td>
                <td>
                    @(item.EmploymentEndDate is null ? "None" : Convert.ToDateTime(item.EmploymentEndDate).ToString("dd/MMMM/yyyy"))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position.Caption)
                </td>
                <td>
                    @Convert.ToDateTime(item.InsertDate).ToString("dd/MMMM/yyyy")
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-outline-secondary" asp-page="./Details" asp-route-id="@item.Id">Details</a>
                    <a class="btn btn-outline-danger" asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.positions-select').select2();
        });
    </script>
}