VacaYAY/VacaYAY.Web/Areas/Contracts/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Contracts.Pages;


[Authorize(Roles = InitialData.AdminRoleName)]
public class DeleteModel : PageModel
{
    private readonly IContractService _contractService;

    public DeleteModel(IContractService contractService)
    {
        _contractService = contractService;
    }

    [BindProperty]
  public Contract Contract { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var contract = await _contractService.GetByIdAsync((int)id);

        if (contract is null)
        {
            return NotFound();
        }
        else 
        {
            Contract = contract;
        }
        return Page();
    }

    public async Task<IActionResult> OnPostAsync(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }
        var contract = await _contractService.GetByIdAsync((int)id);

        if (contract is not null)
        {
            Contract = contract;
            await _contractService.DeleteContractAsync((int)id);
        }

        return RedirectToPage("./Index");
    }
}

VacaYAY/VacaYAY.Web/Areas/Contracts/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.DTOs;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Contracts.Pages;


[Authorize(Roles = InitialData.AdminRoleName)]
public class EditModel : PageModel
{
    private readonly IContractService _contractService;
    private readonly IHttpService _httpService;

    public EditModel(
        IContractService contractService,
        IHttpService httpService)
    {
        _contractService = contractService;
        _httpService = httpService;
    }

    [BindProperty(SupportsGet = true)]
    public ContractDTO ContractDTO { get; set; } = default!;

    [BindProperty]
    public IFormFile? ContractFile { get; set; }

    [BindProperty(SupportsGet = true)]
    public Contract Contract { get; set; } = default!;
    public IList<ContractType> ContractTypes { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        ContractTypes = await _contractService.GetContractTypesAsync();

        if (id is null)
        {
            return NotFound();
        }

        var contract = await _contractService.GetByIdAsync((int)id);
        if (contract is null)
        {
            return NotFound();
        }

        Contract = contract;

        ContractDTO.ContractFile = await _httpService.GetFormFileAsync(contract.DocumentUrl);

        ContractDTO = new ContractDTO()
        {
            Id = contract.Id,
            ContractTypeId = contract.Type.Id,
            EmployeeId = contract.Employee.Id,
            Number = contract.Number,
            StartDate = contract.StartDate,
            EndDate = contract.EndDate
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (ContractFile is not null)
        {
            ContractDTO.ContractFile = ContractFile;
        }

        var contractValidationResult = await _contractService.UpdateContractAsync(ContractDTO);

        if (!contractValidationResult.IsValid)
        {
            ModelState.Clear();
            foreach (var error in contractValidationResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
            return Page();
        }

        Contract = await _contractService.GetByIdAsync(Contract.Id);
        ContractTypes = await _contractService.GetContractTypesAsync();

        return RedirectToPage("./Index");
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages
{
    public class CreateModel : PageModel
    {

        public CreateModel()
        {
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public IActionResult OnPostAsync()
        {
          if (!ModelState.IsValid ||  Employee == null)
            {
                return Page();
            }

            //_context.Employees.Add(Employee);
            //await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages
{
    [Authorize(Roles = InitialData.AdminRoleName)]
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeService _employeeService;

        public DeleteModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        [BindProperty]
      public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var employee = await _employeeService.GetByIdAsync(id);

            if (employee is null)
            {
                return NotFound();
            }
            else 
            {
                Employee = employee;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var employee = await _employeeService.GetByIdAsync(id);

            if (employee is not null)
            {
                Employee = employee;
                
                await _employeeService.SoftDeleteAsync(employee);
            }

            return RedirectToPage("./Index");
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/Employees/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.Employees.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeService _employeeService;
        public DetailsModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

      public required Employee Employee { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var employee = await _employeeService.GetByIdAsync(id);
            if (employee is null)
            {
                return NotFound();
            }
            else 
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.VacationRequests
{
    public class DeleteModel : PageModel
    {
        private readonly IVacationService _vacationService;

        public DeleteModel(IVacationService vacationService)
        {
            _vacationService = vacationService;
        }

        [BindProperty]
        public VacationRequest VacationRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var vacationrequest = await _vacationService.GetVacationRequestByIdAsync((int)id);

            if (vacationrequest is null)
            {
                return NotFound();
            }
            else
            {
                VacationRequest = vacationrequest;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            await _vacationService.DeleteVacationRequestAsync((int)id, User);

            return RedirectToPage("./Index");
        }
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.VacationRequests;

public class DetailsModel : PageModel
{
    private readonly IVacationService _vacationService;

    public DetailsModel(IVacationService vacationService)
    {
        _vacationService = vacationService;
    }

  public VacationRequest VacationRequest { get; set; } = default!; 

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var vacationRequest = await _vacationService.GetVacationRequestByIdAsync((int)id);

        if (vacationRequest is null)
        {
            return NotFound();
        }
        else 
        {
            VacationRequest = vacationRequest;
        }
        return Page();
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.DTOs;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.VacationRequests;

public class EditModel : PageModel
{
    private readonly IVacationService _vacationService;
    private readonly IEmployeeService _employeeService;

    public EditModel(
        IVacationService vacationService,
        IEmployeeService employeeService
        )
    {
        _vacationService = vacationService;
        _employeeService = employeeService;
    }

    [BindProperty]
    public VacationRequestDTO VacationRequestDTO { get; set; } = default!;
    public IList<LeaveType> LeaveTypes { get; set; } = default!;
    public bool IsSameEmployeeAsLoggedInOne = false;
    public bool IsLoggedInEmployeeAdmin => User.IsInRole(InitialData.AdminRoleName);

    public async Task<IActionResult> OnGetAsync(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var loggedInEmployee = await _employeeService.GetLoggedInAsync(User);

        if (loggedInEmployee is null)
        {
            return Unauthorized();
        }

        var vacationRequest = await _vacationService.GetVacationRequestByIdAsync((int)id);
        if (vacationRequest is null)
        {
            return NotFound();
        }

        IsSameEmployeeAsLoggedInOne = loggedInEmployee.Id == vacationRequest.Employee.Id;

        LeaveTypes = await _vacationService.GetLeaveTypesAsync();
        if (!User.IsInRole(InitialData.AdminRoleName))
        {
            LeaveTypes = LeaveTypes.Where(lt => lt.Id != InitialData.CollectiveVacationLeaveType.Id).ToList();
        }

        VacationRequestDTO = new()
        {
            Id = vacationRequest.Id,
            Comment = vacationRequest.Comment,
            VacationReview = vacationRequest.VacationReview is not null
            ? vacationRequest.VacationReview
            : new VacationReview()
            {
                Approved = false,
                Comment = string.Empty,
                Reviewer = default!,
                VacationRequestRefId = vacationRequest.Id,
                VacationRequest = vacationRequest,
                LastYearsDaysTakenOffNumber = 0
            },
            StartDate = vacationRequest.StartDate,
            EndDate = vacationRequest.EndDate,
            Employee = vacationRequest.Employee,
            LeaveType = vacationRequest.LeaveType
        };

        return Page();
    }

    public async Task<IActionResult> OnPostSaveAsync()
    {
        VacationRequest? vacationRequestFromDb = await _vacationService.GetVacationRequestByIdAsync(VacationRequestDTO.Id);

        if (vacationRequestFromDb is null)
        {
            return NotFound();
        }

        var loggedInEmployee = await _employeeService.GetLoggedInAsync(User);

        if (loggedInEmployee is null)
        {
            return Unauthorized();
        }

        IsSameEmployeeAsLoggedInOne = loggedInEmployee.Id == vacationRequestFromDb.Employee.Id;

        LeaveTypes = await _vacationService.GetLeaveTypesAsync();
        if (!User.IsInRole(InitialData.AdminRoleName))
        {
            LeaveTypes = LeaveTypes.Where(lt => lt.Id != InitialData.CollectiveVacationLeaveType.Id).ToList();
        }

        var validationResult = await _vacationService.UpdateVacationRequestAsync(VacationRequestDTO, User);

        if (!validationResult.IsValid)
        {
            ModelState.Clear();
            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }

                VacationRequestDTO.VacationReview ??= new VacationReview()
                {
                    Approved = false,
                    Comment = string.Empty,
                    Reviewer = default!,
                    VacationRequest = default!,
                    LastYearsDaysTakenOffNumber = 0
                };

                return Page();
            }
        }

        return RedirectToPage("./Index");
    }
    public async Task<IActionResult> OnPostUpsertVacationRequestReviewAsync()
    {
        if (VacationRequestDTO.VacationReview.Id == 0)
        {
            await _vacationService.CreateVacationReviewAsync(VacationRequestDTO.VacationReview, VacationRequestDTO.Id, User);
        }
        else
        {
            await _vacationService.UpdateVacationReviewAsync(VacationRequestDTO.VacationReview, VacationRequestDTO.Id, User);
        }

        return RedirectToPage("./Index");
    }

    public async Task<IActionResult> OnPostDeleteVacationRequestReviewAsync()
    {
        await _vacationService.DeleteVacationReviewAsync(VacationRequestDTO.VacationReview.Id, User);

        return RedirectToPage("./Index");
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VacaYAY.Business.Services;
using VacaYAY.Data;
using VacaYAY.Data.DTOs;
using VacaYAY.Data.Models;

namespace VacaYAY.Web.Areas.VacationRequests;

public class IndexModel : PageModel
{
    private readonly IVacationService _vacationService;
    private readonly IEmployeeService _employeeService;

    public IndexModel(
        IVacationService vacationService,
        IEmployeeService employeeService
        )
    {
        _vacationService = vacationService;
        _employeeService = employeeService;
    }

    public IList<VacationRequest> VacationRequests { get; set; } = default!;
    [BindProperty(SupportsGet = true)]
    public VacationRequestSearchFilters Input { get; set; } = default!;
    public IList<LeaveType> LeaveTypes { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync()
    {
        LeaveTypes = await _vacationService.GetLeaveTypesAsync();

        Employee? loggedInEmployee = await _employeeService.GetLoggedInAsync(User);

        if (loggedInEmployee is null)
        {
            return Unauthorized();
        }

        bool isAdmin = await _employeeService.IsInRoleAsync(loggedInEmployee, InitialData.AdminRoleName);
        VacationRequests = await _vacationService.SearchVacationRequestsAsync(loggedInEmployee.Id, isAdmin, Input);

        return Page();
    }

    public async Task<ActionResult> OnPostSearchAsync()
    {
        LeaveTypes = await _vacationService.GetLeaveTypesAsync();

        Employee? loggedInEmployee = await _employeeService.GetLoggedInAsync(User);

        if (loggedInEmployee is null)
        {
            return Unauthorized();
        }

        bool isAdmin = await _employeeService.IsInRoleAsync(loggedInEmployee, InitialData.AdminRoleName);
        VacationRequests = await _vacationService.SearchVacationRequestsAsync(loggedInEmployee.Id, isAdmin, Input);
        
        return Page();
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Create.cshtml
@page
@using VacaYAY.Data.Models;
@model VacaYAY.Web.Areas.VacationRequests.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Vacation request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-floating mb-3">
                <b>&#9432;</b> Vacation days remaining: <b>@(Model.TotalPotentialDaysOff)</b>
                <br/>
                <b>@(Model.PotentialNewDaysOff)</b> from this year's vacation days
                <br />
                <b>@(Model.PotentialLastYearsDaysOff)</b> from last year's vacation days

            </div>
            <div class="form-floating mb-3">
                @Html.DropDownListFor(m => m.LeaveTypeId, new SelectList(@Model.LeaveTypes, nameof(LeaveType.Id), nameof(LeaveType.Name)),
                Model.TotalPotentialDaysOff == 0
                ? new {
                @class="form-control dropdown-toggle",
                @disabled="disabled"
                }
                : new
                {
                @class="form-control dropdown-toggle",
                })
                <label>Leave type</label>
            </div>

            <input type="hidden" asp-for="VacationRequest.Id" />
            <div class="form-floating mb-3">
                <textarea asp-for="VacationRequest.Comment"
                          class="form-control"
                          readonly="@(Model.TotalPotentialDaysOff == 0)"></textarea>
                <label asp-for="VacationRequest.Comment"></label>
                <span asp-validation-for="VacationRequest.Comment" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input type="date" asp-for="VacationRequest.StartDate"
                       class="form-control"
                       min="@DateTime.Now.Date.AddDays(1).ToString("yyyy-MM-dd")"
                       readonly="@(Model.TotalPotentialDaysOff == 0)" />
                <label for="VacationRequest.StartDate">Start date</label>
                <span asp-validation-for="VacationRequest.StartDate" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input type="date" asp-for="VacationRequest.EndDate"
                       class="form-control"
                       min="@DateTime.Now.Date.AddDays(2).ToString("yyyy-MM-dd")"
                       readonly="@(Model.TotalPotentialDaysOff == 0)" />
                <label for="VacationRequest.EndDate">End date</label>
                <span asp-validation-for="VacationRequest.EndDate" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input type="submit" asp-page-handler="Save" class="btn btn-primary"
                       disabled="@(Model.TotalPotentialDaysOff == 0)" />
            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Delete.cshtml
@page
@model VacaYAY.Web.Areas.VacationRequests.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VacationRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VacationRequest.Comment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VacationRequest.Comment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VacationRequest.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VacationRequest.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VacationRequest.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VacationRequest.EndDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="VacationRequest.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Edit.cshtml
@page
@using VacaYAY.Data.Models;
@model VacaYAY.Web.Areas.VacationRequests.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<div class="row justify-content-between">
    <div class="col-md-4">
        <h4>Vacation request for @(Model.VacationRequestDTO.Employee.FirstName + " " + Model.VacationRequestDTO.Employee.LastName)</h4>
        <form method="post">
            @Html.HiddenFor(m => m.VacationRequestDTO.Id)
            <div class="form-floating mb-3">
                @Html.DropDownListFor(m => m.VacationRequestDTO.LeaveType.Id, new SelectList(@Model.LeaveTypes, nameof(LeaveType.Id), nameof(LeaveType.Name)),
                new {@class="form-control dropdown-toggle"})
                <label for="LeaveTypeId">Leave type</label>
            </div>

            <div class="form-floating mb-3">
                <textarea asp-for="VacationRequestDTO.Comment"
                          class="form-control"
                          readonly="@(!Model.IsSameEmployeeAsLoggedInOne)"></textarea>
                <label asp-for="VacationRequestDTO.Comment"></label>
                <span asp-validation-for="VacationRequestDTO.Comment" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="VacationRequestDTO.StartDate"
                       type="date" class="form-control" min="@DateTime.Now.Date.ToString("yyyy-MM-dd")"
                       readonly="@(!Model.IsSameEmployeeAsLoggedInOne)" />
                <label for="VacationRequest.StartDate">Vacation start date</label>
                <span asp-validation-for="VacationRequestDTO.StartDate" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="VacationRequestDTO.EndDate"
                       type="date" class="form-control" min="@DateTime.Now.Date.AddDays(1).ToString("yyyy-MM-dd")"
                       readonly="@(!Model.IsSameEmployeeAsLoggedInOne)" />
                <label for="VacationRequestDTO.EndDate">Vacation end date</label>
                <span asp-validation-for="VacationRequestDTO.EndDate" class="text-danger"></span>
            </div>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input type="submit" asp-page-handler="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <h4>Vacation request review</h4>
        @if (Model.VacationRequestDTO.VacationReview.Id == 0 && !Model.IsLoggedInEmployeeAdmin)
        {
            <h5>Not reviewed yet</h5>
        }
        else
        {
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @Html.HiddenFor(m => m.VacationRequestDTO.VacationReview.Id)
                @Html.HiddenFor(m => m.VacationRequestDTO.Id)
                <div class="form-floating mb-3">
                    <div class="checkbox">
                        @if (Model.IsLoggedInEmployeeAdmin)
                        {
                            <label>
                                @Html.CheckBoxFor(m => m.VacationRequestDTO.VacationReview.Approved)
                                &nbsp;
                                @Html.DisplayNameFor(m => m.VacationRequestDTO.VacationReview.Approved)
                            </label>
                        }
                        else
                        {
                            @(Model.VacationRequestDTO.VacationReview.Approved ? "Approved" : "Rejected")
                        }
                    </div>
                </div>
                <div class="form-floating mb-3">
                    <textarea readonly="@(!Model.IsLoggedInEmployeeAdmin)"
                              asp-for="VacationRequestDTO.VacationReview.Comment" class="form-control"></textarea>
                    <label asp-for="VacationRequestDTO.VacationReview.Comment"></label>
                    <span asp-validation-for="VacationRequestDTO.VacationReview.Comment" class="text-danger"></span>
                </div>
                @if (Model.IsLoggedInEmployeeAdmin)
                {
                    <div class="form-floating mb-3">
                        <button id="vacationRequestReviewSubmit" asp-page-handler="UpsertVacationRequestReview" type="submit" class="w-100 btn btn-primary">
                            @(Model.VacationRequestDTO.VacationReview?.Id != 0 ? "Edit" : "Create")
                        </button>
                    </div>
                    @if (Model.VacationRequestDTO.VacationReview is not null && Model.VacationRequestDTO.VacationReview?.Id != 0)
                    {
                        <div class="form-floating mb-3">
                            <button id="vacationRequestReviewDelete" asp-page-handler="DeleteVacationRequestReview" type="submit" class="w-100 btn btn-danger">Delete</button>
                        </div>
                    }
                }
            </form>
        }
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
            }

VacaYAY/VacaYAY.Web/Areas/VacationRequests/Pages/Index.cshtml
@page
@using VacaYAY.Data.Models;
@using VacaYAY.Data;
@model VacaYAY.Web.Areas.VacationRequests.IndexModel

<h1>Vacation requests</h1>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-page="Create" class="btn btn-outline-primary">Create New</a>
</p>
<h3>Search</h3>
<form method="post">
    <div class="form-floating mb-3">
        @Html.DropDownListFor(m => m.Input.LeaveTypeId, new SelectList(@Model.LeaveTypes, nameof(LeaveType.Id), nameof(LeaveType.Name)), "Any",
        new {@class="form-control dropdown-toggle"})
        <label for="LeaveTypeId">Leave type</label>
    </div>
    @if (User.IsInRole(InitialData.AdminRoleName))
    {
        <div class="form-floating mb-3">
            <input type="text" class="form-control" asp-for="Input.EmployeeFullName" />
            <label asp-for="Input.EmployeeFullName">Employee name</label>
        </div>
    }
    <div class="form-floating mb-3">
        <input type="date" class="form-control" asp-for="Input.StartDate" />
        <label asp-for="Input.StartDate">Vacation start date</label>
    </div>
    <div class="form-floating mb-3">
        <input type="date" class="form-control" asp-for="Input.EndDate" />
        <label asp-for="Input.EndDate">Vacation end date</label>
    </div>
    <button id="searchSubmit" asp-page-handler="Search" type="submit" class="btn btn-primary">Search</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VacationRequests[0].LeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VacationRequests[0].Employee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VacationRequests[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VacationRequests[0].EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VacationRequests[0].Comment)
            </th>
            <th>
                Approved
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.VacationRequests)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.FirstName)
                    @Html.DisplayFor(modelItem => item.Employee.LastName)
                    (@Html.DisplayFor(modelItem => item.Employee.Email))
                </td>
                <td>
                    @Convert.ToDateTime(item.StartDate).ToString("dd/MMMM/yyyy")
                </td>
                <td>
                    @Convert.ToDateTime(item.EndDate).ToString("dd/MMMM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @if (item.VacationReview is not null)
                    {
                        @(item.VacationReview.Approved ? "Yes" : "No")
                    }
                    else
                    {
                        @("Not yet reviewed")

                    }
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-outline-secondary" asp-page="./Details" asp-route-id="@item.Id">Details</a>
                    <a class="btn btn-outline-danger" asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>